// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WepAPICor.net.Models;

public partial class Course
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int Degree { get; set; }

    public int MinDegree { get; set; }

    public int Hours { get; set; }

    public int DeptId { get; set; }

    public virtual ICollection<CrsResult> CrsResults { get; set; } = new List<CrsResult>();

    public virtual Department1 Dept { get; set; }

    public virtual ICollection<Instructor> Instructors { get; set; } = new List<Instructor>();
}