// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WepAPICor.net.Models;

public partial class CrsResult
{
    public int Id { get; set; }

    public int Degree { get; set; }

    public int CrsId { get; set; }

    public int TraineeId { get; set; }

    public virtual Course Crs { get; set; }

    public virtual Trainee Trainee { get; set; }
}