// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WepAPICor.net.Models;

public partial class Employee
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int Salary { get; set; }

    public string JopTitle { get; set; }

    public string ImageUrl { get; set; }

    public string Address { get; set; }

    public int DepartmentId { get; set; }

    public virtual Department1 Department { get; set; }
}